hyperparameters:
  n_channels: 19
  n_samples: 1000
  spike_count: 10
  sfreq: 250
  tr: 2.0

electrode_positions:
  Fp1: [-0.3, 0.8]
  Fp2: [0.3, 0.8]
  F7:  [-0.8, 0.5]
  F8:  [0.8, 0.5]
  F3:  [-0.5, 0.5]
  Fz:  [0, 0.6]
  F4:  [0.5, 0.5]
  T7:  [-1, 0]
  C3:  [-0.5, 0]
  Cz:  [0, 0]
  C4:  [0.5, 0]
  T8:  [1, 0]
  P7:  [-0.8, -0.5]
  P3:  [-0.5, -0.5]
  Pz:  [0, -0.6]
  P4:  [0.5, -0.5]
  P8:  [0.8, -0.5]
  O1:  [-0.3, -0.8]
  Oz:  [0, -0.8]
  O2:  [0.3, -0.8]
